### ISSUE TITLE
Missing translations in crowdin

### ISSUE THREAD

**Issue by Kopierwichtel** [Sleepy334/TransferManagerCE#2]
I'm doing the german translation and noticed a few missing strings in crowd:

Within Export/Import tab all resources
Within the buildings dialog all Materials and in case no Reporter or vehicle is available ("None")
When selecting a warehouse the strings:
"Detected District"
"Apply to All Buildings of Same Type" incl. all related strings
dropdownBuildingPanelOutgoing ...
![CS Screenshot 2022-07-25 191723](https://user-images.githubusercontent.com/4805131/180836674-a24f9fc9-0749-4318-887d-5de28479329f.png)
![CS Screenshot 2022-07-25 191705](https://user-images.githubusercontent.com/4805131/180836688-a13397b5-6058-4538-8ea4-cf50422bf76b.png)

**Comment by Sleepy334** [comment]
Thanks for letting me know. I'll fix it straight away.
