### ISSUE TITLE
Minor threading issues

### ISSUE THREAD

**Issue by krzychu124** [Sleepy334/TransferManagerCE#3]
Hello, 
since I noticed increasing number of people complaining about maxed path units I started reviewing code of mods that can potentially cause that issue.
I haven't found anything big, which is great 👏but still small improvements can be done:

1. Method below has to be called from the simulation thread otherwise waiting for paths won't ensure the expected result (may generate the problem instead of fixing it). Currently it's called from the main thread. You may say that when options panel is open simulation is paused but.. you can't guarantee if that is always the case. 
Also I don't think that maintenance section needs to be available in the main menu 😅 

https://github.com/Sleepy334/TransferManagerCE/blob/main/TransferManagerCE%202.0/Util/PathUnitMaintenance.cs#L5-L18

2. Checking for road access (`PlayerBuildingAI.CheckRoadAccess()`) may trigger notification update but also can trigger Building notification update which then may break render group by updating internals from incorrect thread -> in this case `TransferManagerCE.CustomManager.TransferManagerThread.MatchOfferThread()`

**Comment by Sleepy334** [comment]
Fixed in 2.1
